name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Installe Rust (stable) + composants
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
          # targets: wasm32-unknown-unknown  # si besoin

      # Cache cargo (optionnel mais recommandé)
      - uses: Swatinem/rust-cache@v2

      - name: Cargo fmt
        run: cargo fmt --all -- --check
      - name: Cargo clippy
        run: cargo clippy --workspace --all-targets -- -D warnings
      - name: Cargo test
        run: cargo test --workspace --all-features
      - name: Cargo build
        run: cargo build --workspace --release
