name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target-local
          key: ${{ runner.os }}-cargo-release-${{ hashFiles('**/Cargo.lock') }}

      - name: Build release
        run: cargo build --release -p rss-gui

      - name: Package tar.gz
        run: |
          mkdir -p dist
          cp target-local/release/rss-gui dist/
          tar -C dist -czf rss-gui-linux-x86_64.tar.gz rss-gui

      - name: Install cargo-deb
        run: cargo install cargo-deb

      - name: Build .deb
        run: cargo deb -p rss-gui -- --release

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            rss-gui-linux-x86_64.tar.gz
            target-local/debian/*.deb

  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target-local
          key: ${{ runner.os }}-cargo-release-${{ hashFiles('**/Cargo.lock') }}

      - name: Build release
        run: cargo build --release -p rss-gui

      - name: Package zip
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path dist | Out-Null
          Copy-Item target-local/release/rss-gui.exe dist/rss-gui.exe
          Compress-Archive -Path dist/rss-gui.exe -DestinationPath rss-gui-windows-x86_64.zip -Force

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            rss-gui-windows-x86_64.zip
